eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'