server:
  port: ${PORT:0}
  
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${es.abelfgdeveloper.datasource.database}?currentSchema=${es.abelfgdeveloper.datasource.schema}
    username: ${es.abelfgdeveloper.datasource.username}
    password: ${es.abelfgdeveloper.datasource.password}
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    installed-by: ${spring.application.name}
    
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


logging:
  level:
    root: warn
    '[es.abelfgdeveloper]': info
    '[org.zalando.logbook]': trace
    
    
logbook:
  exclude:
    - /actuator/**
